[build.environment]
  NODE_VERSION = "14"

[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
