[build.environment]
  NODE_VERSION = "14"

[build]
  publish = "dist"
  command = "npm run build"
  ignore = "git diff --exit-code --quiet HEAD^..HEAD . ../simple_dark_theme/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
