[build.environment]
  NODE_VERSION = "15"

[build]
  publish = "dist"
  command = "npm run build"
  ignore = "git diff --exit-code --quiet HEAD^..HEAD ."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
